{
 "title": "ESM Custom Dashboard",
 "tags": [
  "consul",
  "esm"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "HealthCheck Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(check_txn{job=\"Consul-ESM-Agent\"}[$__rate_interval])",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "rate(check_txn{job=\"Consul-ESM-Agent2\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(check_txn{job=\"Consul-ESM-Agent3\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outgoing Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"ens5\"}[$__rate_interval]) * 8",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "go routines in ESM",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "go_goroutines{job=\"Consul-ESM-Agent\"}",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "go_goroutines{job=\"Consul-ESM-Agent2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "go_goroutines{job=\"Consul-ESM-Agent3\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process CPU",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"Consul-ESM-Agent\"}[$__rate_interval])",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "rate(process_cpu_seconds_total{job=\"Consul-ESM-Agent2\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(process_cpu_seconds_total{job=\"Consul-ESM-Agent3\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Check Update Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "rate(checks_update_sum{job=\"Consul-ESM-Agent\"}[$__rate_interval]) / rate(checks_update_count{job=\"Consul-ESM-Agent\"}[$__rate_interval])",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "rate(checks_update_sum{job=\"Consul-ESM-Agent2\"}[$__rate_interval]) / rate(checks_update_count{job=\"Consul-ESM-Agent2\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(checks_update_sum{job=\"Consul-ESM-Agent3\"}[$__rate_interval]) / rate(checks_update_count{job=\"Consul-ESM-Agent3\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}