{
 "title": "New dashboard",
 "time": { "from": "2025-09-22T01:16:10.199Z", "to": "2025-09-22T03:37:49.771Z" },
 "panels": [
  {
   "title": "1. Health Check Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(check_txn{job=\"Consul-ESM-Metrics\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "2. Outgoing Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"ens5\"}[$__rate_interval]) * 8",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "3. Average Check Update Latency (Performance)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(checks_update_sum{job=\"Consul-ESM-Metrics\"}[$__rate_interval]) / rate(checks_update_count{job=\"Consul-ESM-Metrics\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "4. CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"10.0.3.160:9100\"}[$__rate_interval])))",
     "legendFormat": "Consul ESM1"
    },
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"10.0.3.156:9100\"}[$__rate_interval])))",
     "legendFormat": "Consul Server Leader"
    },
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"10.0.3.88:9100\"}[$__rate_interval])))",
     "legendFormat": "Consul ESM 2"
    }
   ]
  },
  {
   "title": "5. Go Routine Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"Consul-ESM-Metrics\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}